version: "3.9"
services:
  mongodb:
    image: 192.168.240.141:5000/mongo:6-jammy
    container_name: mongodb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - 27017:27017
    volumes:
      -  mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - backend
  todo-api:
    image: 192.168.240.141:5000/todo-api:v1.1.0
    container_name: todo-api
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - "mongodb"
    #env_file:
    #  - .env
    ports:
      - "4000:4000"
    environment:
      APP_PORT: 4000
      MONGODB_URI: mongodb://admin:admin@mongodb:27017/GoReact?authSource=admin&authMechanism=SCRAM-SHA-256
    networks:
      - backend

  frontend:
    image: 192.168.240.141:5000/todo-web:v1.1.0
    container_name: frontend
    deploy:
      replicas: 1
    depends_on:
      - "todo-api"
    ports:
      - 8080:80
    environment:
      VITE_API_URL: "http://api.goreact.local"
    volumes:
    - ./conf/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - frontend
    
volumes:
  mongodb_data:
    driver: local

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay

